name: 🚀 Deploy SGF (Grupo Sovel)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repositório
        uses: actions/checkout@v4

      - name: 🧱 Preparar pasta de deploy
        run: |
          mkdir -p docs
          cp -r index.html menu.html registrar.html dashboard.html consultar.html editar.html detalhes.html assets docs/ || true
          touch docs/.nojekyll
          echo "✅ Pasta docs preparada com .nojekyll"

      - name: 🚀 Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
